package UPDATE_MANAGER;


public class FileTypes {

    static int ARTIKEL_INITIAL_IMPORT_FILE = 1111;
    static int ARTIKEL_NEU_ERSTELLT_FILE = 1122;
    static int ARTIKEL_INHALTLICH_VERAENDERT_FILE = 1133;
    static int ARTIKEL_PROTOKOL_ZU_WARENEINGANG = 1144;
    static int ARTIKEL_PROTOKOL_ZU_LIEFERUNG = 1155;
    static int ARTIKEL_PROTOKOL_ZU_AUFTRAG = 1166;

    static int LIEFERSCHEIN_INITIAL_IMPORT_FILE = 2222;
    static int LIEFERSCHEIN_INSERT_EVENT_OHNE_AUFTRAG_FILE = 2233;
    static int LIEFERSCHEIN_INSERT_EVENT_MIT_AUFTRAG_FILE = 2244;

    static int BESTELLUNG_UPDATE_EVENT_FILE = 3333;
    static int BESTELLUNG_INSERT_EVENT_FILE = 3344;
    static int BESTELLUNG_INITIAL_IMPORT_FILE = 3355;

    static int AUFTRAG_INSERT_EVENT_FILE = 4444;
    static int AUFTRAG_INITIAL_IMPORT_FILE = 4455;
    static int AUFTRAG_UPDATE_EVENT_FILE = 4466;

    static int WARENEINGANG_INITIAL_IMPORT_FILE = 5544;
    static int WARENEINGANG_INSERT_EVENT_OHNE_BESTELLUNG_FILE = 5555;
    static int WARENEINGANG_INSERT_EVENT_MIT_BESTELLUNG_FILE = 5566;

    static int WARENGRUPPE_INITIAL_IMPORT_FILE = 6666;
    static int WARENGRUPPE_UPDATE_EVENT_FILE = 6677;
    static int WARENGRUPPE_INSERT_EVENT_FILE = 6688;

    static int LIEFERANTEN_INITIAL_IMPORT_FILE = 7777;
    static int LIEFERANTEN_UPDATE_EVENT_FILE = 7788;
    static int LIEFERANTEN_INSERT_EVENT_FILE = 7799;

    static int WARENAUSGANG_INITIAL_IMPORT_FILE = 8888;
    static int WARENAUSGANG_UPDATE_EVENT_FILE = 8899;
    static int WARENAUSGANG_INSERT_EVENT_FILE = 8877;

}
